#PBS -P <YOUR_PROJECT>
#PBS -l select=1:ncpus=2:mem=8gb
#PBS -l walltime=0:30:00
#PBS -N job01

module load singularity

# Assuming you are running this from your project folder.
cd $PBS_O_WORKDIR

### 1 BUILD IMAGE ###
# First Build only - takes 10 mins, remove after ###
export SINGLUARITY_CACHEDIR=`pwd`
export SINGLUARITY_TMPDIR=`pwd`

singularity build cellranger.img docker://nbutter/cellranger:ubuntu1604

### 2 EXAMPLE WORKFLOW ###
# Remove the build commands above and execute:
singularity run --bind /project:/project cellranger.img /bin/bash -c "cd "$PBS_O_WORKDIR" && export TENX_IGNORE_DEPRECATED_OS=1; cellranger sitecheck > sitecheck.txt"
